---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: secret-generator-sa
  namespace: {{ .Values.namespace }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: secret-generator-role
  namespace: {{ .Values.namespace }}
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "create"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: secret-generator-rb
  namespace: {{ .Values.namespace }}
subjects:
  - kind: ServiceAccount
    name: secret-generator-sa
    namespace: {{ .Values.namespace }}
roleRef:
  kind: Role
  name: secret-generator-role
  apiGroup: rbac.authorization.k8s.io

---
---
apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Values.env }}-secret-generator"
  namespace: "{{ .Values.namespace }}"
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  template:
    spec:
      serviceAccountName: secret-generator-sa
      restartPolicy: OnFailure
      containers:
      - name: create-secret
        image: bitnami/kubectl:latest
        command:
          - /bin/sh
          - -c
          - |
            if ! kubectl get secret app-secret -n {{ .Values.namespace }} >/dev/null 2>&1; then
              echo "Secret not found. Creating..."
              kubectl create secret generic app-secret \
                -n {{ .Values.namespace }} \
                --from-literal=SECRET_KEY=$(head /dev/urandom | tr -dc A-Za-z0-9 | head -c 32)
            else
              echo "Secret already exists. Skipping creation."
            fi