apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Values.env }}-secret-generator"
  namespace: "{{ .Values.namespace }}"
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
      - name: create-secret
        image: bitnami/kubectl:latest
        command:
          - /bin/sh
          - -c
          - |
            if ! kubectl get secret app-secret -n {{ .Values.namespace }} >/dev/null 2>&1; then
              echo "Secret not found. Creating..."
              kubectl create secret generic app-secret                 -n {{ .Values.namespace }}                 --from-literal=SECRET_KEY=$(head /dev/urandom | tr -dc A-Za-z0-9 | head -c 32)
            else
              echo "Secret already exists. Skipping creation."
            fi
